<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

One dimensional array:


In [ ]:
import numpy as np
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

Two-dimensional array:


In [ ]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [ ]:
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
ind

array([[0, 1],
       [1, 0]])

In [ ]:
np.take_along_axis(x, ind, axis=0)  # same as np.sort(x, axis=0)

array([[0, 2],
       [2, 3]])

In [ ]:
ind = np.argsort(x, axis=1)  # sorts along last axis (across)
ind

array([[0, 1],
       [0, 1]])

In [ ]:
np.take_along_axis(x, ind, axis=1)  # same as np.sort(x, axis=1)

array([[0, 3],
       [2, 2]])

Indices of the sorted elements of a N-dimensional array:


In [ ]:
ind = np.unravel_index(np.argsort(x, axis=None), x.shape)
ind

(array([0, 1, 1, 0]), array([0, 0, 1, 1]))

In [ ]:
x[ind]  # same as np.sort(x, axis=None)

array([0, 2, 2, 3])

Sorting with keys:


In [ ]:
x = np.array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])
x

array([(1, 0), (0, 1)],
      dtype=[('x', '<i4'), ('y', '<i4')])

In [ ]:
np.argsort(x, order=('x','y'))

array([1, 0])

In [ ]:
np.argsort(x, order=('y','x'))

array([0, 1])