<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
rng = np.random.default_rng()
rng.integers(2, size=10)

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0])  # random

In [ ]:
rng.integers(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Generate a 2 x 4 array of ints between 0 and 4, inclusive:


In [ ]:
rng.integers(5, size=(2, 4))

array([[4, 0, 2, 1],
       [3, 2, 2, 0]])  # random

Generate a 1 x 3 array with 3 different upper bounds


In [ ]:
rng.integers(1, [3, 5, 10])

array([2, 2, 9])  # random

Generate a 1 by 3 array with 3 different lower bounds


In [ ]:
rng.integers([1, 5, 7], 10)

array([9, 8, 7])  # random

Generate a 2 by 4 array using broadcasting with dtype of uint8


In [ ]:
rng.integers([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)

array([[ 8,  6,  9,  7],
       [ 1, 16,  9, 12]], dtype=uint8)  # random