<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([(1, 2.0), (1, 2.0)],
    dtype=[('x', np.int64), ('y', np.float64)])
a

array([(1, 2.), (1, 2.)], dtype=[('x', '<i8'), ('y', '<f8')])

Here, each element consists of two fields: x (and int), and y (a float).
This is known as a structured array.  The different fields are analogous
to columns in a spread-sheet.  The different fields can be accessed as
one would a dictionary:


In [ ]:
a['x']

array([1, 1])

In [ ]:
a['y']

array([2., 2.])

Record arrays allow us to access fields as properties:


In [ ]:
ar = np.rec.array(a)
ar.x

array([1, 1])

In [ ]:
ar.y

array([2., 2.])