<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

The most common use of this function is to build a block matrix:


In [ ]:
import numpy as np
A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([
    [A,               np.zeros((2, 3))],
    [np.ones((3, 2)), B               ]
])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

With a list of depth 1, `block` can be used as `hstack`:


In [ ]:
np.block([1, 2, 3])              # hstack([1, 2, 3])

array([1, 2, 3])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.block([a, b, 10])             # hstack([a, b, 10])

array([ 1,  2,  3,  4,  5,  6, 10])

In [ ]:
A = np.ones((2, 2), int)
B = 2 * A
np.block([A, B])                 # hstack([A, B])

array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

With a list of depth 2, `block` can be used in place of `vstack`:


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.block([[a], [b]])             # vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A = np.ones((2, 2), int)
B = 2 * A
np.block([[A], [B]])             # vstack([A, B])

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

It can also be used in place of `atleast_1d` and `atleast_2d`:


In [ ]:
a = np.array(0)
b = np.array([1])
np.block([a])                    # atleast_1d(a)

array([0])

In [ ]:
np.block([b])                    # atleast_1d(b)

array([1])

In [ ]:
np.block([[a]])                  # atleast_2d(a)

array([[0]])

In [ ]:
np.block([[b]])                  # atleast_2d(b)

array([[1]])