<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],
       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Sum over axes 0 and 2. The result has same number of dimensions
as the original array:


In [ ]:
np.apply_over_axes(np.sum, a, [0,2])

array([[[ 60],
        [ 92],
        [124]]])

Tuple axis arguments to ufuncs are equivalent:


In [ ]:
np.sum(a, axis=(0,2), keepdims=True)

array([[[ 60],
        [ 92],
        [124]]])