<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([[10, 7, 4], [3, 2, 1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [ ]:
np.percentile(a, 50)

3.5

In [ ]:
np.percentile(a, 50, axis=0)

array([6.5, 4.5, 2.5])

In [ ]:
np.percentile(a, 50, axis=1)

array([7.,  2.])

In [ ]:
np.percentile(a, 50, axis=1, keepdims=True)

array([[7.],
       [2.]])

In [ ]:
m = np.percentile(a, 50, axis=0)
out = np.zeros_like(m)
np.percentile(a, 50, axis=0, out=out)

array([6.5, 4.5, 2.5])

In [ ]:
m

array([6.5, 4.5, 2.5])

In [ ]:
b = a.copy()
np.percentile(b, 50, axis=1, overwrite_input=True)

array([7.,  2.])

In [ ]:
assert not np.all(a == b)

The different methods can be visualized graphically:

.. code-block:: python

    import matplotlib.pyplot as plt

    a = np.arange(4)
    p = np.linspace(0, 100, 6001)
    ax = plt.gca()
    lines = [
        ('linear', '-', 'C0'),
        ('inverted_cdf', ':', 'C1'),
        # Almost the same as `inverted_cdf`:
        ('averaged_inverted_cdf', '-.', 'C1'),
        ('closest_observation', ':', 'C2'),
        ('interpolated_inverted_cdf', '--', 'C1'),
        ('hazen', '--', 'C3'),
        ('weibull', '-.', 'C4'),
        ('median_unbiased', '--', 'C5'),
        ('normal_unbiased', '-.', 'C6'),
        ]
    for method, style, color in lines:
        ax.plot(
            p, np.percentile(a, p, method=method),
            label=method, linestyle=style, color=color)
    ax.set(
        title='Percentiles for different methods and data: ' + str(a),
        xlabel='Percentile',
        ylabel='Estimated percentile value',
        yticks=a)
    ax.legend(bbox_to_anchor=(1.03, 1))
    plt.tight_layout()
    plt.show()
