<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [ ]:
np.max(a)           # Maximum of the flattened array

3

In [ ]:
np.max(a, axis=0)   # Maxima along the first axis

array([2, 3])

In [ ]:
np.max(a, axis=1)   # Maxima along the second axis

array([1, 3])

In [ ]:
np.max(a, where=[False, True], initial=-1, axis=0)

array([-1,  3])

In [ ]:
b = np.arange(5, dtype=float)
b[2] = np.nan
np.max(b)

np.float64(nan)

In [ ]:
np.max(b, where=~np.isnan(b), initial=-1)

4.0

In [ ]:
np.nanmax(b)

4.0

You can use an initial value to compute the maximum of an empty slice, or
to initialize it to a different value:


In [ ]:
np.max([[-50], [10]], axis=-1, initial=0)

array([ 0, 10])

Notice that the initial value is used as one of the elements for which the
maximum is determined, unlike for the default argument Python's max
function, which is only used for empty iterables.


In [ ]:
np.max([5], initial=6)

6

In [ ]:
max([5], default=6)

5