<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.rec.array(a)

rec.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],
          dtype=int64)

In [ ]:
b = [(1, 1), (2, 4), (3, 9)]
c = np.rec.array(b, formats = ['i2', 'f2'], names = ('x', 'y'))
c

rec.array([(1, 1.), (2, 4.), (3, 9.)],
          dtype=[('x', '<i2'), ('y', '<f2')])

In [ ]:
c.x

array([1, 2, 3], dtype=int16)

In [ ]:
c.y

array([1.,  4.,  9.], dtype=float16)

In [ ]:
r = np.rec.array(['abc','def'], names=['col1','col2'])
print(r.col1)

abc

In [ ]:
r.col1

array('abc', dtype='<U3')

In [ ]:
r.col2

array('def', dtype='<U3')