<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [ ]:
a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

Return the unique rows of a 2D array


In [ ]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 0, 0], [2, 3, 4]])

Return the indices of the original array that give the unique values:


In [ ]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_index=True)
u

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
indices

array([0, 1, 3])

In [ ]:
a[indices]

array(['a', 'b', 'c'], dtype='<U1')

Reconstruct the input array from the unique values and inverse:


In [ ]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices = np.unique(a, return_inverse=True)
u

array([1, 2, 3, 4, 6])

In [ ]:
indices

array([0, 1, 4, 3, 1, 2, 1])

In [ ]:
u[indices]

array([1, 2, 6, 4, 2, 3, 2])

Reconstruct the input values from the unique values and counts:


In [ ]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
values, counts = np.unique(a, return_counts=True)
values

array([1, 2, 3, 4, 6])

In [ ]:
counts

array([1, 3, 1, 1, 1])

In [ ]:
np.repeat(values, counts)

array([1, 2, 2, 2, 3, 4, 6])    # original order not preserved