<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

One dimensional array:


In [ ]:
import numpy as np
x = np.array([3, 4, 2, 1])
x[np.argpartition(x, 3)]

array([2, 1, 3, 4]) # may vary

In [ ]:
x[np.argpartition(x, (1, 3))]

array([1, 2, 3, 4]) # may vary

In [ ]:
x = [3, 4, 2, 1]
np.array(x)[np.argpartition(x, 3)]

array([2, 1, 3, 4]) # may vary

Multi-dimensional array:


In [ ]:
x = np.array([[3, 4, 2], [1, 3, 1]])
index_array = np.argpartition(x, kth=1, axis=-1)
# below is the same as np.partition(x, kth=1)
np.take_along_axis(x, index_array, axis=-1)

array([[2, 3, 4],
       [1, 1, 3]])