<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

To intersect more than two arrays, use functools.reduce:


In [ ]:
from functools import reduce
reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([3])

To return the indices of the values common to the input arrays
along with the intersected values:


In [ ]:
x = np.array([1, 1, 2, 3, 4])
y = np.array([2, 1, 4, 6])
xy, x_ind, y_ind = np.intersect1d(x, y, return_indices=True)
x_ind, y_ind

(array([0, 2, 4]), array([1, 0, 2]))

In [ ]:
xy, x[x_ind], y[y_ind]

(array([1, 2, 4]), array([1, 2, 4]), array([1, 2, 4]))