<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Consider four points in different quadrants:


In [ ]:
import numpy as np
x = np.array([-1, +1, +1, -1])
y = np.array([-1, -1, +1, +1])
np.arctan2(y, x) * 180 / np.pi

array([-135.,  -45.,   45.,  135.])

Note the order of the parameters. `arctan2` is defined also when `x2` = 0
and at several other special points, obtaining values in
the range ``[-pi, pi]``:


In [ ]:
np.arctan2([1., -1.], [0., 0.])

array([ 1.57079633, -1.57079633])

In [ ]:
np.arctan2([0., 0., np.inf], [+0., -0., np.inf])

array([0.        , 3.14159265, 0.78539816])