<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

`default_rng` is the recommended constructor for the random number class
`Generator`. Here are several ways we can construct a random 
number generator using `default_rng` and the `Generator` class. 

Here we use `default_rng` to generate a random float:


In [ ]:
import numpy as np
rng = np.random.default_rng(12345)
print(rng)

Generator(PCG64)

In [ ]:
rfloat = rng.random()
rfloat

0.22733602246716966

In [ ]:
type(rfloat)

<class 'float'>

Here we use `default_rng` to generate 3 random integers between 0 
(inclusive) and 10 (exclusive):


In [ ]:
import numpy as np
rng = np.random.default_rng(12345)
rints = rng.integers(low=0, high=10, size=3)
rints

array([6, 2, 7])

In [ ]:
type(rints[0])

<class 'numpy.int64'>

Here we specify a seed so that we have reproducible results:


In [ ]:
import numpy as np
rng = np.random.default_rng(seed=42)
print(rng)

Generator(PCG64)

In [ ]:
arr1 = rng.random((3, 3))
arr1

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

If we exit and restart our Python interpreter, we'll see that we
generate the same random numbers again:


In [ ]:
import numpy as np
rng = np.random.default_rng(seed=42)
arr2 = rng.random((3, 3))
arr2

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])