<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
from numpy.linalg import matrix_power
i = np.array([[0, 1], [-1, 0]]) # matrix equiv. of the imaginary unit
matrix_power(i, 3) # should = -i

array([[ 0, -1],
       [ 1,  0]])

In [ ]:
matrix_power(i, 0)

array([[1, 0],
       [0, 1]])

In [ ]:
matrix_power(i, -3) # should = 1/(-i) = i, but w/ f.p. elements

array([[ 0.,  1.],
       [-1.,  0.]])

Somewhat more sophisticated example


In [ ]:
q = np.zeros((4, 4))
q[0:2, 0:2] = -i
q[2:4, 2:4] = i
q # one of the three quaternion units not equal to 1

array([[ 0., -1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0., -1.,  0.]])

In [ ]:
matrix_power(q, 2) # = -np.eye(4)

array([[-1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0., -1.]])