<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.multiply.reduce([2,3,5])

30

A multi-dimensional array example:


In [ ]:
X = np.arange(8).reshape((2,2,2))
X

array([[[0, 1],
        [2, 3]],
       [[4, 5],
        [6, 7]]])

In [ ]:
np.add.reduce(X, 0)

array([[ 4,  6],
       [ 8, 10]])

In [ ]:
np.add.reduce(X) # confirm: default axis value is 0

array([[ 4,  6],
       [ 8, 10]])

In [ ]:
np.add.reduce(X, 1)

array([[ 2,  4],
       [10, 12]])

In [ ]:
np.add.reduce(X, 2)

array([[ 1,  5],
       [ 9, 13]])

You can use the ``initial`` keyword argument to initialize the reduction
with a different value, and ``where`` to select specific elements to include:


In [ ]:
np.add.reduce([10], initial=5)

15

In [ ]:
np.add.reduce(np.ones((2, 2, 2)), axis=(0, 2), initial=10)

array([14., 14.])

In [ ]:
a = np.array([10., np.nan, 10])
np.add.reduce(a, where=~np.isnan(a))

20.0

Allows reductions of empty arrays where they would normally fail, i.e.
for ufuncs without an identity.


In [ ]:
np.minimum.reduce([], initial=np.inf)

inf

In [ ]:
np.minimum.reduce([[1., 2.], [3., 4.]], initial=10., where=[True, False])

array([ 1., 10.])

In [ ]:
np.minimum.reduce([])

Traceback (most recent call last):
    ...
ValueError: zero-size array to reduction operation minimum which has no identity