<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Shrinking an array: array is flattened (in the order that the data are
stored in memory), resized, and reshaped:


In [ ]:
import numpy as np

In [ ]:
a = np.array([[0, 1], [2, 3]], order='C')
a.resize((2, 1))
a

array([[0],
       [1]])

In [ ]:
a = np.array([[0, 1], [2, 3]], order='F')
a.resize((2, 1))
a

array([[0],
       [2]])

Enlarging an array: as above, but missing entries are filled with zeros:


In [ ]:
b = np.array([[0, 1], [2, 3]])
b.resize(2, 3) # new_shape parameter doesn't have to be a tuple
b

array([[0, 1, 2],
       [3, 0, 0]])

Referencing an array prevents resizing...


In [ ]:
c = a
a.resize((1, 1))


Traceback (most recent call last):
ValueError: cannot resize an array that references or is referenced ...

Unless `refcheck` is False:


In [ ]:
a.resize((1, 1), refcheck=False)
a

array([[0]])

In [ ]:
c

array([[0]])