<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Throw a dice 20 times:


In [ ]:
rng = np.random.default_rng()
rng.multinomial(20, [1/6.]*6, size=1)

array([[4, 1, 7, 5, 2, 1]])  # random

It landed 4 times on 1, once on 2, etc.

Now, throw the dice 20 times, and 20 times again:


In [ ]:
rng.multinomial(20, [1/6.]*6, size=2)

array([[3, 4, 3, 3, 4, 3],
       [2, 4, 3, 4, 0, 7]])  # random

For the first run, we threw 3 times 1, 4 times 2, etc.  For the second,
we threw 2 times 1, 4 times 2, etc.

Now, do one experiment throwing the dice 10 time, and 10 times again,
and another throwing the dice 20 times, and 20 times again:


In [ ]:
rng.multinomial([[10], [20]], [1/6.]*6, size=(2, 2))

array([[[2, 4, 0, 1, 2, 1],
        [1, 3, 0, 3, 1, 2]],
       [[1, 4, 4, 4, 4, 3],
        [3, 3, 2, 5, 5, 2]]])  # random

The first array shows the outcomes of throwing the dice 10 times, and
the second shows the outcomes from throwing the dice 20 times.

A loaded die is more likely to land on number 6:


In [ ]:
rng.multinomial(100, [1/7.]*5 + [2/7.])

array([11, 16, 14, 17, 16, 26])  # random

Simulate 10 throws of a 4-sided die and 20 throws of a 6-sided die


In [ ]:
rng.multinomial([10, 20],[[1/4]*4 + [0]*2, [1/6]*6])

array([[2, 1, 4, 3, 0, 0],
       [3, 3, 3, 6, 1, 4]], dtype=int64)  # random

Generate categorical random variates from two categories where the
first has 3 outcomes and the second has 2.


In [ ]:
rng.multinomial(1, [[.1, .5, .4 ], [.3, .7, .0]])

array([[0, 0, 1],
       [0, 1, 0]], dtype=int64)  # random

``argmax(axis=-1)`` is then used to return the categories.


In [ ]:
pvals = [[.1, .5, .4 ], [.3, .7, .0]]
rvs = rng.multinomial(1, pvals, size=(4,2))
rvs.argmax(axis=-1)

array([[0, 1],
       [2, 0],
       [2, 1],
       [2, 0]], dtype=int64)  # random

The same output dimension can be produced using broadcasting.


In [ ]:
rvs = rng.multinomial([[1]] * 4, pvals)
rvs.argmax(axis=-1)

array([[0, 1],
       [2, 0],
       [2, 1],
       [2, 0]], dtype=int64)  # random

The probability inputs should be normalized. As an implementation
detail, the value of the last entry is ignored and assumed to take
up any leftover probability mass, but this should not be relied on.
A biased coin which has twice as much weight on one side as on the
other should be sampled like so:


In [ ]:
rng.multinomial(100, [1.0 / 3, 2.0 / 3])  # RIGHT

array([38, 62])  # random

not like:


In [ ]:
rng.multinomial(100, [1.0, 2.0])  # WRONG

Traceback (most recent call last):
ValueError: pvals < 0, pvals > 1 or pvals contains NaNs