<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

A 3-dimensional array of size 3 x 3 x 3, summed over each of its
three axes:


In [ ]:
import numpy as np

In [ ]:
x = np.arange(27).reshape((3,3,3))
x

array([[[ 0,  1,  2],
      [ 3,  4,  5],
      [ 6,  7,  8]],
      [[ 9, 10, 11],
      [12, 13, 14],
      [15, 16, 17]],
      [[18, 19, 20],
      [21, 22, 23],
      [24, 25, 26]]])

In [ ]:
x.sum(axis=0)

array([[27, 30, 33],
      [36, 39, 42],
      [45, 48, 51]])

In [ ]:
# for sum, axis is the first keyword, so we may omit it,
# specifying only its value
x.sum(0), x.sum(1), x.sum(2)

(array([[27, 30, 33],
      [36, 39, 42],
      [45, 48, 51]]),
array([[ 9, 12, 15],
      [36, 39, 42],
      [63, 66, 69]]),
array([[ 3, 12, 21],
      [30, 39, 48],
      [57, 66, 75]]))