<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

Create a set of indices to access the diagonal of a (4, 4) array:


In [ ]:
di = np.diag_indices(4)
di

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [ ]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a[di] = 100
a

array([[100,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9, 100,  11],
       [ 12,  13,  14, 100]])

Now, we create indices to manipulate a 3-D array:


In [ ]:
d3 = np.diag_indices(2, 3)
d3

(array([0, 1]), array([0, 1]), array([0, 1]))

And use it to set the diagonal of an array of zeros to 1:


In [ ]:
a = np.zeros((2, 2, 2), dtype=int)
a[d3] = 1
a

array([[[1, 0],
        [0, 0]],
       [[0, 0],
        [0, 1]]])