<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
from numpy.polynomial import polyutils as pu
old_domain = (-1,1)
new_domain = (0,2*np.pi)
x = np.linspace(-1,1,6); x

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [ ]:
x_out = pu.mapdomain(x, old_domain, new_domain); x_out

array([ 0.        ,  1.25663706,  2.51327412,  3.76991118,  5.02654825, # may vary
        6.28318531])

In [ ]:
x - pu.mapdomain(x_out, new_domain, old_domain)

array([0., 0., 0., 0., 0., 0.])

Also works for complex numbers (and thus can be used to map any line in
the complex plane to any other line therein).


In [ ]:
i = complex(0,1)
old = (-1 - i, 1 + i)
new = (-1 + i, 1 - i)
z = np.linspace(old[0], old[1], 6); z

array([-1. -1.j , -0.6-0.6j, -0.2-0.2j,  0.2+0.2j,  0.6+0.6j,  1. +1.j ])

In [ ]:
new_z = pu.mapdomain(z, old, new); new_z

array([-1.0+1.j , -0.6+0.6j, -0.2+0.2j,  0.2-0.2j,  0.6-0.6j,  1.0-1.j ]) # may vary