<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

np.array allows to specify whether the array is written in C-contiguous
order (last index varies the fastest), or FORTRAN-contiguous order in
memory (first index varies the fastest).


In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]], order='C')
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.isfortran(a)

False

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]], order='F')
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.isfortran(b)

True

The transpose of a C-ordered array is a FORTRAN-ordered array.


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]], order='C')
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.isfortran(a)

False

In [ ]:
b = a.T
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.isfortran(b)

True

C-ordered arrays evaluate as False even if they are also FORTRAN-ordered.


In [ ]:
np.isfortran(np.array([1, 2], order='F'))

False