<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j], dtype=np.complex128)
np.isreal(a)

array([False,  True,  True,  True,  True, False])

The function does not work on string arrays.


In [ ]:
a = np.array([2j, "a"], dtype=np.str_)
np.isreal(a)  # returns the result of `"" == 0` currently.

array([False, False])

Returns True for all elements that either have no ``.imag`` attribute
or for which that attribute is zero:


In [ ]:
a = np.array([1, "2", 3+4j], dtype=np.object_)
np.isreal(a)

array([ True,  True,  False])